window.OEM_DATA = [
  {
    "id": "ola-electric",
    "name": "Ola Electric Mobility Ltd",
    "sector": "EV 2W",
    "chemistry": "NMC 811",
    "imports_2024": 950.0,
    "imports_2025": 1350.0,
    "mwh_2025": 168.0,
    "recycling_partner": "In-talks",
    "cpcb_status": "Registered",
    "contact_person": "Sandeep Kumar (Head of Procurement)",
    "email": "sandeep.k@olaelectric.com",
    "notes": "Building their own Cell Gigafactory in Tamil Nadu but currently importing massive volumes of LG Chem cells. Current EPR liability is extremely high. They represent a high-volume target that requires immediate short-term certificates."
  },
  {
    "id": "ather-energy",
    "name": "Ather Energy Pvt Ltd",
    "sector": "EV 2W",
    "chemistry": "NMC 622",
    "imports_2024": 380.0,
    "imports_2025": 480.0,
    "mwh_2025": 60.0,
    "recycling_partner": "None",
    "cpcb_status": "Registered",
    "contact_person": "Vidya Ramachandran (VP Supply Chain)",
    "email": "vidya.r@atherenergy.com",
    "notes": "Highly premium EV scooter manufacturer. Imports NMC cylindrical cells. Has no exclusive public recycling tie-ups and is under pressure to meet the 80% collection target for FY 2025-26. Prime low-hanging fruit."
  },
  {
    "id": "tata-motors",
    "name": "Tata Motors Ltd / Tata AutoComp",
    "sector": "EV 4W",
    "chemistry": "LFP",
    "imports_2024": 2900.0,
    "imports_2025": 3800.0,
    "mwh_2025": 380.0,
    "recycling_partner": "Partnered",
    "cpcb_status": "Registered",
    "contact_person": "R. K. Gupta (EVP EV Procurement)",
    "email": "rk.gupta@tatamotors.com",
    "notes": "Uses Tata Group synergies (Tata Chemicals and Tata AutoComp Gotion) for battery packaging and recycling. Difficult to break in, though their massive LFP volume represents a future target for high-purity refining."
  },
  {
    "id": "tvs-motor",
    "name": "TVS Motor Company Ltd",
    "sector": "EV 2W",
    "chemistry": "NMC 532",
    "imports_2024": 600.0,
    "imports_2025": 850.0,
    "mwh_2025": 106.0,
    "recycling_partner": "None",
    "cpcb_status": "Registered",
    "contact_person": "Animesh Saxena (GM Sourcing)",
    "email": "animesh.s@tvsmotor.com",
    "notes": "Massive scaling of iQube EV scooter. Sourcing cells from Samsung SDI. Does not have an exclusive recycling partner. Perfect candidate for MiniMines because of their high-quality NMC chemistry cell imports."
  },
  {
    "id": "mahindra-electric",
    "name": "Mahindra & Mahindra Ltd",
    "sector": "EV 4W",
    "chemistry": "LFP",
    "imports_2024": 1100.0,
    "imports_2025": 1600.0,
    "mwh_2025": 160.0,
    "recycling_partner": "In-talks",
    "cpcb_status": "Registered",
    "contact_person": "Abhay Deodhar (Head of Sustainability)",
    "email": "deodhar.abhay@mahindra.com",
    "notes": "Launching their BE (Born Electric) SUV range, importing battery packs from VW/BYD. Exploring multiple recycling partners. Highly interested in circular closed-loop recovery of battery raw materials."
  },
  {
    "id": "coslight-india",
    "name": "Coslight India Telecom Pvt Ltd",
    "sector": "Telecom / ESS",
    "chemistry": "LFP",
    "imports_2024": 750.0,
    "imports_2025": 920.0,
    "mwh_2025": 92.0,
    "recycling_partner": "None",
    "cpcb_status": "Registered",
    "contact_person": "N. K. Sharma (Technical Director)",
    "email": "nksharma@coslightindia.in",
    "notes": "Major supplier of Lithium Iron Phosphate (LFP) batteries to telecom towers (Jio, Airtel). Their batteries are distributed across thousands of sites and are now reaching end-of-life. Looking for a collection/recycling partner to clear old field batteries."
  },
  {
    "id": "hero-motocorp",
    "name": "Hero MotoCorp Ltd (Vida)",
    "sector": "EV 2W",
    "chemistry": "NMC 811",
    "imports_2024": 200.0,
    "imports_2025": 320.0,
    "mwh_2025": 40.0,
    "recycling_partner": "None",
    "cpcb_status": "Registered",
    "contact_person": "K. Srinivas (Sustainability Lead)",
    "email": "k.srinivas@heromotocorp.com",
    "notes": "Expanding their Vida EV portfolio. Sourcing high-nickel NMC cells. No recycling tie-ups announced yet. Strong brand credibility makes them a prestigious target partner for MiniMines."
  },
  {
    "id": "greaves-electric",
    "name": "Greaves Electric Mobility (Ampere)",
    "sector": "EV 2W",
    "chemistry": "LFP",
    "imports_2024": 180.0,
    "imports_2025": 240.0,
    "mwh_2025": 24.0,
    "recycling_partner": "None",
    "cpcb_status": "Registered",
    "contact_person": "Prasad Varma (VP Sourcing)",
    "email": "prasad.varma@greaveselectric.com",
    "notes": "Focusing on mass-market EV 2W and 3W. Sourcing cost-effective LFP cells. Seeking low-cost compliance solutions. Excellent candidate for volume recycling."
  }
];
